#!/bin/bash

set -e

yarn solium --dir evm/
yarn solium --dir examples/
yarn lint:evm && yarn lint:examples

yarn workspace chainlink run truffle test

yarn workspace example-uptime-sla run truffle test --network test

yarn workspace example-echo-server run truffle test --network test
